service: AppUserManagementService

provider:
    name: aws
    runtime: nodejs12.x
    iamRoleStatements: # permissions for all of your functions can be set here
        - Effect: Allow
          Action: # Gives permission to DynamoDB tables
              - dynamodb:Query
              - dynamodb:GetItem
              - dynamodb:PutItem
              - dynamodb:UpdateItem
          Resource: 'arn:aws:dynamodb:*:*:*'

functions:
    getUserAppsMetadata:
        handler: dist/index/aws.getUserAppsMetadata
        events:
            - http:
                  path: /getUserAppsMetadata
                  method: get
    getAppUsers:
        handler: dist/index/aws.getAppUsers
        events:
            - http:
                  path: /getAppUsers
                  method: post
    addUserToApp:
        handler: dist/index/aws.addUserToApp
        events:
            - http:
                  path: /addUserToApp
                  method: post
    addUsersToApp:
        handler: dist/index/aws.addUsersToApp
        events:
            - http:
                  path: /addUsersToApp
                  method: post
    updateUserAppPermissions:
        handler: dist/index/aws.updateUserAppPermissions
        events:
            - http:
                  path: /updateUserAppPermissions
                  method: post
    removeUserFromApp:
        handler: dist/index/aws.removeUserFromApp
        events:
            - http:
                  path: /removeUserFromApp
                  method: post
    removeUserFromAllApps:
        handler: dist/index/aws.removeUserFromAllApps
        events:
            - http:
                  path: /removeUserFromAllApps
                  method: post

resources:
    Resources:
        UserApps:
            Type: AWS::DynamoDB::Table
            Properties:
                TableName: UserApps
                AttributeDefinitions:
                    - AttributeName: userIdWorkplaceId
                      AttributeType: S
                    - AttributeName: appId
                      AttributeType: S
                KeySchema:
                    - AttributeName: userIdWorkplaceId
                      KeyType: HASH
                    - AttributeName: appId
                      KeyType: RANGE
                GlobalSecondaryIndexes:
                    - IndexName: appId-index
                      KeySchema:
                          - AttributeName: appId
                            KeyType: HASH
                      Projection:
                          ProjectionType: ALL
                BillingMode: PAY_PER_REQUEST
